// ===== 4. SINIF 36 HAFTALIK YILLIK PLAN (MEB matrisi uyumlu) =====
// yillikPlan[hafta][dersKey] -> { konu, kazanimlar: [{kod, aciklama}] }

export const DERS_BILGI = {
  turkce:    { ad: "Turkce", ikon: "📖" },
  matematik: { ad: "Matematik", ikon: "📐" },
  fen:       { ad: "Fen Bilimleri", ikon: "🔬" },
  sosyal:    { ad: "Sosyal Bilgiler", ikon: "🌍" },
  ingilizce: { ad: "Ingilizce", ikon: "🔤" },
  dkab:      { ad: "Din Kulturu ve Ahlak Bilgisi", ikon: "🕌" },
  insanhak:  { ad: "Insan Haklari Yurttaslik ve Demokrasi", ikon: "⚖️" },
  trafik:    { ad: "Trafik Guvenligi", ikon: "🚦" },
  gorsel:    { ad: "Gorsel Sanatlar", ikon: "🎨" },
  muzik:     { ad: "Muzik", ikon: "🎵" },
  beden:     { ad: "Beden Egitimi ve Oyun", ikon: "⚽" }
};

// Tekrar eden ders icerikleri (kisa tutmak icin)
const T_OKUMA = { konu: "1. Tema: Okuma Kulturu", kazanimlar: [{ kod: "T.4.3.1", aciklama: "Metni akici ve dogru okur" }, { kod: "T.4.3.19", aciklama: "Okudugunu anlar ve yorumlar" }] };
const T_MILLI = { konu: "2. Tema: Milli Mucadele ve Ataturk", kazanimlar: [{ kod: "T.4.3.20", aciklama: "Metnin ana fikrini belirler" }, { kod: "T.4.4.7", aciklama: "Duygu ve dusuncelerini yaziyla anlatir" }] };
const T_BILIM = { konu: "3. Tema: Bilim ve Teknoloji", kazanimlar: [{ kod: "T.4.3.23", aciklama: "Bilgilendirici metinleri anlar" }, { kod: "T.4.4.11", aciklama: "Aciklayici metin yazar" }] };
const T_DOGA  = { konu: "4. Tema: Doga ve Evren", kazanimlar: [{ kod: "T.4.2.4", aciklama: "Dinledigini anlar ve ozetler" }, { kod: "T.4.3.14", aciklama: "Metindeki ayrintilari bulur" }] };

const ING = {
  u1: { konu: "U1 Classroom Rules", kazanimlar: [{ kod: "E4.1.L1", aciklama: "Sinif kurallarini Ingilizce anlar" }] },
  u2: { konu: "U2 Nationality", kazanimlar: [{ kod: "E4.2.S1", aciklama: "Milliyetleri Ingilizce ifade eder" }] },
  u3: { konu: "U3 Cartoon Characters", kazanimlar: [{ kod: "E4.3.S1", aciklama: "Karakterleri Ingilizce tanitir" }] },
  u4: { konu: "U4 Free Time", kazanimlar: [{ kod: "E4.4.L2", aciklama: "Bos zaman etkinliklerini Ingilizce anlatir" }] }
};
const DKAB = {
  d1: { konu: "1. Unite: Gunluk Dini Ifadeler", kazanimlar: [{ kod: "DKAB.4.1.1", aciklama: "Gunluk dini ifadeleri tanir" }] },
  d2: { konu: "1. Unite: Dilek ve Dualar", kazanimlar: [{ kod: "DKAB.4.1.2", aciklama: "Dilek ve dualari ogrenir" }] },
  d3: { konu: "2. Unite: Islamin Sartlari", kazanimlar: [{ kod: "DKAB.4.2.1", aciklama: "Islamin sartlarini sayar" }] },
  d4: { konu: "2. Unite: Imanin Sartlari", kazanimlar: [{ kod: "DKAB.4.2.2", aciklama: "Imanin sartlarini ogrenir" }] }
};
const IHD = {
  h1: { konu: "1. Unite: Insan Olmak", kazanimlar: [{ kod: "IHD.4.1.1", aciklama: "Insan olmanin degerini fark eder" }] },
  h2: { konu: "2. Unite: Hak ve Ozgurlukler", kazanimlar: [{ kod: "IHD.4.2.1", aciklama: "Temel hak ve ozgurlukleri kavrar" }] },
  h3: { konu: "Sorumluluklarimiz", kazanimlar: [{ kod: "IHD.4.2.2", aciklama: "Bireysel sorumluluklarini bilir" }] },
  h4: { konu: "Adalet ve Esitlik", kazanimlar: [{ kod: "IHD.4.3.1", aciklama: "Adalet ve esitligi ornekler" }] }
};
const TRF = {
  t1: { konu: "1. Unite: Trafikte Guvenlik", kazanimlar: [{ kod: "TG.4.1.1", aciklama: "Trafikte guvenli davranislari ogrenir" }] },
  t2: { konu: "Guvenli Gecis Yerleri", kazanimlar: [{ kod: "TG.4.1.5", aciklama: "Guvenli gecis yerlerini kullanir" }] },
  t3: { konu: "Trafik Isaretleri", kazanimlar: [{ kod: "TG.4.1.7", aciklama: "Trafik isaretlerini tanir" }] },
  t4: { konu: "Ambulans ve Itfaiye Gecis Ustunlugu", kazanimlar: [{ kod: "TG.4.1.9", aciklama: "Oncelikli araclari taniyip yol verir" }] }
};
const GORSEL = [
  { konu: "Cizgi ve bicim calismalari", kazanimlar: [{ kod: "G.S.4.1.2", aciklama: "Cizgi ile anlatim yapar" }] },
  { konu: "Renk calismalari", kazanimlar: [{ kod: "G.S.4.2.1", aciklama: "Renkleri taniyip kullanir" }] },
  { konu: "Desen ve doku", kazanimlar: [{ kod: "G.S.4.2.3", aciklama: "Desen ve dokuyu eserinde kullanir" }] },
  { konu: "Serbest tasarim", kazanimlar: [{ kod: "G.S.4.3.1", aciklama: "Ozgun tasarim yapar" }] }
];
const MUZIK = [
  { konu: "Ritim calismalari", kazanimlar: [{ kod: "MU.4.1.2", aciklama: "Basit ritimleri uygular" }] },
  { konu: "Sarki soyleme", kazanimlar: [{ kod: "MU.4.2.1", aciklama: "Sarki soyler" }] },
  { konu: "Muzik dinleme", kazanimlar: [{ kod: "MU.4.3.1", aciklama: "Dinledigi muzigi yorumlar" }] },
  { konu: "Muzikli oyunlar", kazanimlar: [{ kod: "MU.4.4.1", aciklama: "Muzikli oyunlara katilir" }] }
];
const BEDEN = [
  { konu: "Temel hareketler", kazanimlar: [{ kod: "OFE.4.1.3", aciklama: "Temel hareketleri yapar" }] },
  { konu: "Koordinasyon oyunlari", kazanimlar: [{ kod: "OFE.4.2.1", aciklama: "Koordinasyon gerektiren oyunlar oynar" }] },
  { konu: "Takim oyunlari", kazanimlar: [{ kod: "OFE.4.3.1", aciklama: "Takim oyunlarinda is birligi yapar" }] },
  { konu: "Hareket ve denge", kazanimlar: [{ kod: "OFE.4.2.4", aciklama: "Denge gerektiren hareketleri yapar" }] }
];

// Yan branslar 4 haftalik dongu: u1/d1/h1/t1/s1 -> u2/d2/h2/t2/s2 -> ...
function yanBrans(n) { // n: 1..4 dongu indeksi
  return {
    ingilizce: [ING.u1, ING.u2, ING.u3, ING.u4][n-1],
    dkab: [DKAB.d1, DKAB.d2, DKAB.d3, DKAB.d4][n-1],
    insanhak: [IHD.h1, IHD.h2, IHD.h3, IHD.h4][n-1],
    trafik: [TRF.t1, TRF.t2, TRF.t3, TRF.t4][n-1],
    gorsel: GORSEL[n-1],
    muzik: MUZIK[n-1],
    beden: BEDEN[n-1]
  };
}

export const YILLIK_PLAN = {
  1:  { turkce: T_OKUMA, matematik: { konu: "1. Unite: Dogal Sayilar / Toplama", kazanimlar: [{ kod: "M.4.1.1.1", aciklama: "Dort basamakli dogal sayilari okur ve yazar" }, { kod: "M.4.1.2.1", aciklama: "Dogal sayilarla toplama islemi yapar" }] }, fen: { konu: "1. Unite: Yer Kabugu ve Dunyamiz", kazanimlar: [{ kod: "F.B.4.1.1.1", aciklama: "Yer kabugunun nelerden olustugunu aciklar" }, { kod: "F.B.4.1.2.1", aciklama: "Dunyamizin katmanlarini tanir" }] }, sosyal: { konu: "1. Unite: Birey ve Toplum", kazanimlar: [{ kod: "SB.4.1.1", aciklama: "Bireysel farkliliklari tanir" }, { kod: "SB.4.1.3", aciklama: "Cocuk haklarini ornekler" }] }, ...yanBrans(1) },
  2:  { turkce: T_OKUMA, matematik: { konu: "1. Unite: Dogal Sayilar / Toplama", kazanimlar: [{ kod: "M.4.1.1.1", aciklama: "Dort basamakli dogal sayilari okur ve yazar" }, { kod: "M.4.1.2.1", aciklama: "Dogal sayilarla toplama islemi yapar" }] }, fen: { konu: "1. Unite: Yer Kabugu ve Dunyamiz", kazanimlar: [{ kod: "F.B.4.1.1.1", aciklama: "Yer kabugunun nelerden olustugunu aciklar" }, { kod: "F.B.4.1.2.1", aciklama: "Dunyamizin katmanlarini tanir" }] }, sosyal: { konu: "1. Unite: Birey ve Toplum", kazanimlar: [{ kod: "SB.4.1.1", aciklama: "Bireysel farkliliklari tanir" }, { kod: "SB.4.1.3", aciklama: "Cocuk haklarini ornekler" }] }, ...yanBrans(2) },
  3:  { turkce: T_OKUMA, matematik: { konu: "1. Unite: Dogal Sayilar / Toplama", kazanimlar: [{ kod: "M.4.1.1.1", aciklama: "Dort basamakli dogal sayilari okur ve yazar" }, { kod: "M.4.1.2.1", aciklama: "Dogal sayilarla toplama islemi yapar" }] }, fen: { konu: "1. Unite: Yer Kabugu ve Dunyamiz", kazanimlar: [{ kod: "F.B.4.1.1.1", aciklama: "Yer kabugunun nelerden olustugunu aciklar" }, { kod: "F.B.4.1.2.1", aciklama: "Dunyamizin katmanlarini tanir" }] }, sosyal: { konu: "1. Unite: Birey ve Toplum", kazanimlar: [{ kod: "SB.4.1.1", aciklama: "Bireysel farkliliklari tanir" }, { kod: "SB.4.1.3", aciklama: "Cocuk haklarini ornekler" }] }, ...yanBrans(3) },
  4:  { turkce: T_OKUMA, matematik: { konu: "1. Unite: Dogal Sayilar / Toplama", kazanimlar: [{ kod: "M.4.1.1.1", aciklama: "Dort basamakli dogal sayilari okur ve yazar" }, { kod: "M.4.1.2.1", aciklama: "Dogal sayilarla toplama islemi yapar" }] }, fen: { konu: "1. Unite: Yer Kabugu ve Dunyamiz", kazanimlar: [{ kod: "F.B.4.1.1.1", aciklama: "Yer kabugunun nelerden olustugunu aciklar" }, { kod: "F.B.4.1.2.1", aciklama: "Dunyamizin katmanlarini tanir" }] }, sosyal: { konu: "1. Unite: Birey ve Toplum", kazanimlar: [{ kod: "SB.4.1.1", aciklama: "Bireysel farkliliklari tanir" }, { kod: "SB.4.1.3", aciklama: "Cocuk haklarini ornekler" }] }, ...yanBrans(4) },
  5:  { turkce: T_OKUMA, matematik: { konu: "1. Unite: Dogal Sayilar / Toplama", kazanimlar: [{ kod: "M.4.1.1.1", aciklama: "Dort basamakli dogal sayilari okur ve yazar" }, { kod: "M.4.1.2.1", aciklama: "Dogal sayilarla toplama islemi yapar" }] }, fen: { konu: "1. Unite: Yer Kabugu ve Dunyamiz", kazanimlar: [{ kod: "F.B.4.1.1.1", aciklama: "Yer kabugunun nelerden olustugunu aciklar" }, { kod: "F.B.4.1.2.1", aciklama: "Dunyamizin katmanlarini tanir" }] }, sosyal: { konu: "1. Unite: Birey ve Toplum", kazanimlar: [{ kod: "SB.4.1.1", aciklama: "Bireysel farkliliklari tanir" }, { kod: "SB.4.1.3", aciklama: "Cocuk haklarini ornekler" }] }, ...yanBrans(1) },
  6:  { turkce: T_OKUMA, matematik: { konu: "2. Unite: Cikarma ve Carpma", kazanimlar: [{ kod: "M.4.1.3.1", aciklama: "Dogal sayilarla cikarma islemi yapar" }, { kod: "M.4.1.4.1", aciklama: "Dogal sayilarla carpma islemi yapar" }] }, fen: { konu: "1. Unite: Yer Kabugu ve Dunyamiz", kazanimlar: [{ kod: "F.B.4.1.1.1", aciklama: "Yer kabugunun nelerden olustugunu aciklar" }, { kod: "F.B.4.1.2.1", aciklama: "Dunyamizin katmanlarini tanir" }] }, sosyal: { konu: "2. Unite: Kultur ve Miras", kazanimlar: [{ kod: "SB.4.2.1", aciklama: "Milli kulturumuzun ogelerini tanir" }, { kod: "SB.4.2.4", aciklama: "Tarihi ve kulturel mirasi korur" }] }, ...yanBrans(2) },
  7:  { turkce: T_OKUMA, matematik: { konu: "2. Unite: Cikarma ve Carpma", kazanimlar: [{ kod: "M.4.1.3.1", aciklama: "Dogal sayilarla cikarma islemi yapar" }, { kod: "M.4.1.4.1", aciklama: "Dogal sayilarla carpma islemi yapar" }] }, fen: { konu: "2. Unite: Besinlerimiz", kazanimlar: [{ kod: "F.B.4.2.1.1", aciklama: "Besin cesitlerini tanir" }, { kod: "F.B.4.2.1.3", aciklama: "Dengeli beslenmenin onemini aciklar" }] }, sosyal: { konu: "2. Unite: Kultur ve Miras", kazanimlar: [{ kod: "SB.4.2.1", aciklama: "Milli kulturumuzun ogelerini tanir" }, { kod: "SB.4.2.4", aciklama: "Tarihi ve kulturel mirasi korur" }] }, ...yanBrans(3) },
  8:  { turkce: T_OKUMA, matematik: { konu: "2. Unite: Cikarma ve Carpma", kazanimlar: [{ kod: "M.4.1.3.1", aciklama: "Dogal sayilarla cikarma islemi yapar" }, { kod: "M.4.1.4.1", aciklama: "Dogal sayilarla carpma islemi yapar" }] }, fen: { konu: "2. Unite: Besinlerimiz", kazanimlar: [{ kod: "F.B.4.2.1.1", aciklama: "Besin cesitlerini tanir" }, { kod: "F.B.4.2.1.3", aciklama: "Dengeli beslenmenin onemini aciklar" }] }, sosyal: { konu: "2. Unite: Kultur ve Miras", kazanimlar: [{ kod: "SB.4.2.1", aciklama: "Milli kulturumuzun ogelerini tanir" }, { kod: "SB.4.2.4", aciklama: "Tarihi ve kulturel mirasi korur" }] }, ...yanBrans(4) },
  9:  { turkce: T_OKUMA, matematik: { konu: "2. Unite: Cikarma ve Carpma", kazanimlar: [{ kod: "M.4.1.3.1", aciklama: "Dogal sayilarla cikarma islemi yapar" }, { kod: "M.4.1.4.1", aciklama: "Dogal sayilarla carpma islemi yapar" }] }, fen: { konu: "2. Unite: Besinlerimiz", kazanimlar: [{ kod: "F.B.4.2.1.1", aciklama: "Besin cesitlerini tanir" }, { kod: "F.B.4.2.1.3", aciklama: "Dengeli beslenmenin onemini aciklar" }] }, sosyal: { konu: "2. Unite: Kultur ve Miras", kazanimlar: [{ kod: "SB.4.2.1", aciklama: "Milli kulturumuzun ogelerini tanir" }, { kod: "SB.4.2.4", aciklama: "Tarihi ve kulturel mirasi korur" }] }, ...yanBrans(1) },
  10: { turkce: T_MILLI, matematik: { konu: "3. Unite: Bolme ve Kesirler", kazanimlar: [{ kod: "M.4.1.5.1", aciklama: "Dogal sayilarla bolme islemi yapar" }, { kod: "M.4.1.6.2", aciklama: "Kesirleri tanir ve gosterir" }] }, fen: { konu: "2. Unite: Besinlerimiz", kazanimlar: [{ kod: "F.B.4.2.1.1", aciklama: "Besin cesitlerini tanir" }, { kod: "F.B.4.2.1.3", aciklama: "Dengeli beslenmenin onemini aciklar" }] }, sosyal: { konu: "2. Unite: Kultur ve Miras", kazanimlar: [{ kod: "SB.4.2.1", aciklama: "Milli kulturumuzun ogelerini tanir" }, { kod: "SB.4.2.4", aciklama: "Tarihi ve kulturel mirasi korur" }] }, ...yanBrans(2) },
  11: { turkce: T_MILLI, matematik: { konu: "3. Unite: Bolme ve Kesirler", kazanimlar: [{ kod: "M.4.1.5.1", aciklama: "Dogal sayilarla bolme islemi yapar" }, { kod: "M.4.1.6.2", aciklama: "Kesirleri tanir ve gosterir" }] }, fen: { konu: "2. Unite: Besinlerimiz", kazanimlar: [{ kod: "F.B.4.2.1.1", aciklama: "Besin cesitlerini tanir" }, { kod: "F.B.4.2.1.3", aciklama: "Dengeli beslenmenin onemini aciklar" }] }, sosyal: { konu: "2. Unite: Kultur ve Miras", kazanimlar: [{ kod: "SB.4.2.1", aciklama: "Milli kulturumuzun ogelerini tanir" }, { kod: "SB.4.2.4", aciklama: "Tarihi ve kulturel mirasi korur" }] }, ...yanBrans(3) },
  12: { turkce: T_MILLI, matematik: { konu: "3. Unite: Bolme ve Kesirler", kazanimlar: [{ kod: "M.4.1.5.1", aciklama: "Dogal sayilarla bolme islemi yapar" }, { kod: "M.4.1.6.2", aciklama: "Kesirleri tanir ve gosterir" }] }, fen: { konu: "2. Unite: Besinlerimiz", kazanimlar: [{ kod: "F.B.4.2.1.1", aciklama: "Besin cesitlerini tanir" }, { kod: "F.B.4.2.1.3", aciklama: "Dengeli beslenmenin onemini aciklar" }] }, sosyal: { konu: "3. Unite: Insanlar, Yerler, Cevre", kazanimlar: [{ kod: "SB.4.3.1", aciklama: "Yasadigi cevreyi tanir" }, { kod: "SB.4.3.6", aciklama: "Cevre sorunlarina cozum onerir" }] }, ...yanBrans(4) },
  13: { turkce: T_MILLI, matematik: { konu: "3. Unite: Bolme ve Kesirler", kazanimlar: [{ kod: "M.4.1.5.1", aciklama: "Dogal sayilarla bolme islemi yapar" }, { kod: "M.4.1.6.2", aciklama: "Kesirleri tanir ve gosterir" }] }, fen: { konu: "3. Unite: Kuvvetin Etkileri", kazanimlar: [{ kod: "F.B.4.3.1.1", aciklama: "Kuvvetin cisimler uzerindeki etkilerini kesfeder" }, { kod: "F.B.4.3.2.1", aciklama: "Itme ve cekme kuvvetlerini ornekler" }] }, sosyal: { konu: "3. Unite: Insanlar, Yerler, Cevre", kazanimlar: [{ kod: "SB.4.3.1", aciklama: "Yasadigi cevreyi tanir" }, { kod: "SB.4.3.6", aciklama: "Cevre sorunlarina cozum onerir" }] }, ...yanBrans(1) },
  14: { turkce: T_MILLI, matematik: { konu: "3. Unite: Bolme ve Kesirler", kazanimlar: [{ kod: "M.4.1.5.1", aciklama: "Dogal sayilarla bolme islemi yapar" }, { kod: "M.4.1.6.2", aciklama: "Kesirleri tanir ve gosterir" }] }, fen: { konu: "3. Unite: Kuvvetin Etkileri", kazanimlar: [{ kod: "F.B.4.3.1.1", aciklama: "Kuvvetin cisimler uzerindeki etkilerini kesfeder" }, { kod: "F.B.4.3.2.1", aciklama: "Itme ve cekme kuvvetlerini ornekler" }] }, sosyal: { konu: "3. Unite: Insanlar, Yerler, Cevre", kazanimlar: [{ kod: "SB.4.3.1", aciklama: "Yasadigi cevreyi tanir" }, { kod: "SB.4.3.6", aciklama: "Cevre sorunlarina cozum onerir" }] }, ...yanBrans(2) },
  15: { turkce: T_MILLI, matematik: { konu: "Donem Sonu Tekrar", kazanimlar: [{ kod: "M.4.1.6.3", aciklama: "Kesirlerle ilgili genel tekrar yapar" }] }, fen: { konu: "3. Unite: Kuvvetin Etkileri", kazanimlar: [{ kod: "F.B.4.3.1.1", aciklama: "Kuvvetin cisimler uzerindeki etkilerini kesfeder" }, { kod: "F.B.4.3.2.1", aciklama: "Itme ve cekme kuvvetlerini ornekler" }] }, sosyal: { konu: "3. Unite: Insanlar, Yerler, Cevre", kazanimlar: [{ kod: "SB.4.3.1", aciklama: "Yasadigi cevreyi tanir" }, { kod: "SB.4.3.6", aciklama: "Cevre sorunlarina cozum onerir" }] }, ...yanBrans(3) },
  16: { turkce: T_MILLI, matematik: { konu: "Donem Sonu / 2. Donem Basi Tekrar", kazanimlar: [{ kod: "M.4.1.6.3", aciklama: "Genel tekrar ve degerlendirme" }] }, fen: { konu: "3. Unite: Kuvvetin Etkileri", kazanimlar: [{ kod: "F.B.4.3.1.1", aciklama: "Kuvvetin cisimler uzerindeki etkilerini kesfeder" }, { kod: "F.B.4.3.2.1", aciklama: "Itme ve cekme kuvvetlerini ornekler" }] }, sosyal: { konu: "3. Unite: Insanlar, Yerler, Cevre", kazanimlar: [{ kod: "SB.4.3.1", aciklama: "Yasadigi cevreyi tanir" }, { kod: "SB.4.3.6", aciklama: "Cevre sorunlarina cozum onerir" }] }, ...yanBrans(4) },
  17: { turkce: T_MILLI, matematik: { konu: "2. Donem Basi Tekrar", kazanimlar: [{ kod: "M.4.1.6.3", aciklama: "Genel tekrar ve degerlendirme" }] }, fen: { konu: "3. Unite: Kuvvetin Etkileri", kazanimlar: [{ kod: "F.B.4.3.1.1", aciklama: "Kuvvetin cisimler uzerindeki etkilerini kesfeder" }, { kod: "F.B.4.3.2.1", aciklama: "Itme ve cekme kuvvetlerini ornekler" }] }, sosyal: { konu: "3. Unite: Insanlar, Yerler, Cevre", kazanimlar: [{ kod: "SB.4.3.1", aciklama: "Yasadigi cevreyi tanir" }, { kod: "SB.4.3.6", aciklama: "Cevre sorunlarina cozum onerir" }] }, ...yanBrans(1) },
  18: { turkce: T_MILLI, matematik: { konu: "2. Donem Basi Tekrar", kazanimlar: [{ kod: "M.4.1.6.3", aciklama: "Genel tekrar ve degerlendirme" }] }, fen: { konu: "3. Unite: Kuvvetin Etkileri", kazanimlar: [{ kod: "F.B.4.3.1.1", aciklama: "Kuvvetin cisimler uzerindeki etkilerini kesfeder" }, { kod: "F.B.4.3.2.1", aciklama: "Itme ve cekme kuvvetlerini ornekler" }] }, sosyal: { konu: "4. Unite: Bilim, Teknoloji, Toplum", kazanimlar: [{ kod: "SB.4.4.1", aciklama: "Bilim ve teknolojinin gelisimini ornekler" }, { kod: "SB.4.4.3", aciklama: "Teknolojinin hayatimiza etkisini aciklar" }] }, ...yanBrans(2) },
  19: { turkce: T_BILIM, matematik: { konu: "4. Unite: Kesirlerde Islem / Ondalik", kazanimlar: [{ kod: "M.4.1.7.1", aciklama: "Kesirlerle toplama-cikarma yapar" }, { kod: "M.4.1.7.2", aciklama: "Ondalik gosterimi tanir" }] }, fen: { konu: "4. Unite: Maddenin Ozellikleri", kazanimlar: [{ kod: "F.B.4.4.1.1", aciklama: "Maddenin olculebilir ozelliklerini tanir" }, { kod: "F.B.4.4.2.1", aciklama: "Maddenin hallerini ayirt eder" }] }, sosyal: { konu: "4. Unite: Bilim, Teknoloji, Toplum", kazanimlar: [{ kod: "SB.4.4.1", aciklama: "Bilim ve teknolojinin gelisimini ornekler" }, { kod: "SB.4.4.3", aciklama: "Teknolojinin hayatimiza etkisini aciklar" }] }, ...yanBrans(3) },
  20: { turkce: T_BILIM, matematik: { konu: "4. Unite: Kesirlerde Islem / Ondalik", kazanimlar: [{ kod: "M.4.1.7.1", aciklama: "Kesirlerle toplama-cikarma yapar" }, { kod: "M.4.1.7.2", aciklama: "Ondalik gosterimi tanir" }] }, fen: { konu: "4. Unite: Maddenin Ozellikleri", kazanimlar: [{ kod: "F.B.4.4.1.1", aciklama: "Maddenin olculebilir ozelliklerini tanir" }, { kod: "F.B.4.4.2.1", aciklama: "Maddenin hallerini ayirt eder" }] }, sosyal: { konu: "4. Unite: Bilim, Teknoloji, Toplum", kazanimlar: [{ kod: "SB.4.4.1", aciklama: "Bilim ve teknolojinin gelisimini ornekler" }, { kod: "SB.4.4.3", aciklama: "Teknolojinin hayatimiza etkisini aciklar" }] }, ...yanBrans(4) },
  21: { turkce: T_BILIM, matematik: { konu: "4. Unite: Kesirlerde Islem / Ondalik", kazanimlar: [{ kod: "M.4.1.7.1", aciklama: "Kesirlerle toplama-cikarma yapar" }, { kod: "M.4.1.7.2", aciklama: "Ondalik gosterimi tanir" }] }, fen: { konu: "4. Unite: Maddenin Ozellikleri", kazanimlar: [{ kod: "F.B.4.4.1.1", aciklama: "Maddenin olculebilir ozelliklerini tanir" }, { kod: "F.B.4.4.2.1", aciklama: "Maddenin hallerini ayirt eder" }] }, sosyal: { konu: "4. Unite: Bilim, Teknoloji, Toplum", kazanimlar: [{ kod: "SB.4.4.1", aciklama: "Bilim ve teknolojinin gelisimini ornekler" }, { kod: "SB.4.4.3", aciklama: "Teknolojinin hayatimiza etkisini aciklar" }] }, ...yanBrans(1) },
  22: { turkce: T_BILIM, matematik: { konu: "4. Unite: Kesirlerde Islem / Ondalik", kazanimlar: [{ kod: "M.4.1.7.1", aciklama: "Kesirlerle toplama-cikarma yapar" }, { kod: "M.4.1.7.2", aciklama: "Ondalik gosterimi tanir" }] }, fen: { konu: "4. Unite: Maddenin Ozellikleri", kazanimlar: [{ kod: "F.B.4.4.1.1", aciklama: "Maddenin olculebilir ozelliklerini tanir" }, { kod: "F.B.4.4.2.1", aciklama: "Maddenin hallerini ayirt eder" }] }, sosyal: { konu: "4. Unite: Bilim, Teknoloji, Toplum", kazanimlar: [{ kod: "SB.4.4.1", aciklama: "Bilim ve teknolojinin gelisimini ornekler" }, { kod: "SB.4.4.3", aciklama: "Teknolojinin hayatimiza etkisini aciklar" }] }, ...yanBrans(2) },
  23: { turkce: T_BILIM, matematik: { konu: "4. Unite: Kesirlerde Islem / Ondalik", kazanimlar: [{ kod: "M.4.1.7.1", aciklama: "Kesirlerle toplama-cikarma yapar" }, { kod: "M.4.1.7.2", aciklama: "Ondalik gosterimi tanir" }] }, fen: { konu: "4. Unite: Maddenin Ozellikleri", kazanimlar: [{ kod: "F.B.4.4.1.1", aciklama: "Maddenin olculebilir ozelliklerini tanir" }, { kod: "F.B.4.4.2.1", aciklama: "Maddenin hallerini ayirt eder" }] }, sosyal: { konu: "5. Unite: Uretim, Dagitim, Tuketim", kazanimlar: [{ kod: "SB.4.5.2", aciklama: "Uretim ve tuketim iliskisini aciklar" }, { kod: "SB.4.5.4", aciklama: "Bilincli tuketici olmayi ogrenir" }] }, ...yanBrans(3) },
  24: { turkce: T_BILIM, matematik: { konu: "5. Unite: Geometrik Cisimler / Zaman Olcme", kazanimlar: [{ kod: "M.4.2.1.1", aciklama: "Geometrik cisimleri tanir" }, { kod: "M.4.3.5.1", aciklama: "Zamani olcer ve hesaplar" }] }, fen: { konu: "4. Unite: Maddenin Ozellikleri", kazanimlar: [{ kod: "F.B.4.4.1.1", aciklama: "Maddenin olculebilir ozelliklerini tanir" }, { kod: "F.B.4.4.2.1", aciklama: "Maddenin hallerini ayirt eder" }] }, sosyal: { konu: "5. Unite: Uretim, Dagitim, Tuketim", kazanimlar: [{ kod: "SB.4.5.2", aciklama: "Uretim ve tuketim iliskisini aciklar" }, { kod: "SB.4.5.4", aciklama: "Bilincli tuketici olmayi ogrenir" }] }, ...yanBrans(4) },
  25: { turkce: T_BILIM, matematik: { konu: "5. Unite: Geometrik Cisimler / Zaman Olcme", kazanimlar: [{ kod: "M.4.2.1.1", aciklama: "Geometrik cisimleri tanir" }, { kod: "M.4.3.5.1", aciklama: "Zamani olcer ve hesaplar" }] }, fen: { konu: "4. Unite: Maddenin Ozellikleri", kazanimlar: [{ kod: "F.B.4.4.1.1", aciklama: "Maddenin olculebilir ozelliklerini tanir" }, { kod: "F.B.4.4.2.1", aciklama: "Maddenin hallerini ayirt eder" }] }, sosyal: { konu: "5. Unite: Uretim, Dagitim, Tuketim", kazanimlar: [{ kod: "SB.4.5.2", aciklama: "Uretim ve tuketim iliskisini aciklar" }, { kod: "SB.4.5.4", aciklama: "Bilincli tuketici olmayi ogrenir" }] }, ...yanBrans(1) },
  26: { turkce: T_BILIM, matematik: { konu: "5. Unite: Geometrik Cisimler / Zaman Olcme", kazanimlar: [{ kod: "M.4.2.1.1", aciklama: "Geometrik cisimleri tanir" }, { kod: "M.4.3.5.1", aciklama: "Zamani olcer ve hesaplar" }] }, fen: { konu: "5. Unite: Aydinlatma ve Ses Teknolojileri", kazanimlar: [{ kod: "F.B.4.5.1.1", aciklama: "Gecmisten gunumuze aydinlatma araclarini tanir" }, { kod: "F.B.4.5.3.1", aciklama: "Ses kaydeden teknolojileri ornekler" }] }, sosyal: { konu: "5. Unite: Uretim, Dagitim, Tuketim", kazanimlar: [{ kod: "SB.4.5.2", aciklama: "Uretim ve tuketim iliskisini aciklar" }, { kod: "SB.4.5.4", aciklama: "Bilincli tuketici olmayi ogrenir" }] }, ...yanBrans(2) },
  27: { turkce: T_BILIM, matematik: { konu: "5. Unite: Geometrik Cisimler / Zaman Olcme", kazanimlar: [{ kod: "M.4.2.1.1", aciklama: "Geometrik cisimleri tanir" }, { kod: "M.4.3.5.1", aciklama: "Zamani olcer ve hesaplar" }] }, fen: { konu: "5. Unite: Aydinlatma ve Ses Teknolojileri", kazanimlar: [{ kod: "F.B.4.5.1.1", aciklama: "Gecmisten gunumuze aydinlatma araclarini tanir" }, { kod: "F.B.4.5.3.1", aciklama: "Ses kaydeden teknolojileri ornekler" }] }, sosyal: { konu: "5. Unite: Uretim, Dagitim, Tuketim", kazanimlar: [{ kod: "SB.4.5.2", aciklama: "Uretim ve tuketim iliskisini aciklar" }, { kod: "SB.4.5.4", aciklama: "Bilincli tuketici olmayi ogrenir" }] }, ...yanBrans(3) },
  28: { turkce: T_DOGA, matematik: { konu: "5. Unite: Geometrik Cisimler / Zaman Olcme", kazanimlar: [{ kod: "M.4.2.1.1", aciklama: "Geometrik cisimleri tanir" }, { kod: "M.4.3.5.1", aciklama: "Zamani olcer ve hesaplar" }] }, fen: { konu: "5. Unite: Aydinlatma ve Ses Teknolojileri", kazanimlar: [{ kod: "F.B.4.5.1.1", aciklama: "Gecmisten gunumuze aydinlatma araclarini tanir" }, { kod: "F.B.4.5.3.1", aciklama: "Ses kaydeden teknolojileri ornekler" }] }, sosyal: { konu: "6. Unite: Etkin Vatandaslik", kazanimlar: [{ kod: "SB.4.6.2", aciklama: "Vatandaslik gorevlerini ornekler" }, { kod: "SB.4.6.3", aciklama: "Toplumsal birlik ve dayanismayi aciklar" }] }, ...yanBrans(4) },
  29: { turkce: T_DOGA, matematik: { konu: "6. Unite: Veri Isleme / Cevre Olcme", kazanimlar: [{ kod: "M.4.3.1.1", aciklama: "Veri toplar ve tabloya isler" }, { kod: "M.4.2.3.1", aciklama: "Cevre uzunlugunu hesaplar" }] }, fen: { konu: "5. Unite: Aydinlatma ve Ses Teknolojileri", kazanimlar: [{ kod: "F.B.4.5.1.1", aciklama: "Gecmisten gunumuze aydinlatma araclarini tanir" }, { kod: "F.B.4.5.3.1", aciklama: "Ses kaydeden teknolojileri ornekler" }] }, sosyal: { konu: "6. Unite: Etkin Vatandaslik", kazanimlar: [{ kod: "SB.4.6.2", aciklama: "Vatandaslik gorevlerini ornekler" }, { kod: "SB.4.6.3", aciklama: "Toplumsal birlik ve dayanismayi aciklar" }] }, ...yanBrans(1) },
  30: { turkce: T_DOGA, matematik: { konu: "6. Unite: Veri Isleme / Cevre Olcme", kazanimlar: [{ kod: "M.4.3.1.1", aciklama: "Veri toplar ve tabloya isler" }, { kod: "M.4.2.3.1", aciklama: "Cevre uzunlugunu hesaplar" }] }, fen: { konu: "5. Unite: Aydinlatma ve Ses Teknolojileri", kazanimlar: [{ kod: "F.B.4.5.1.1", aciklama: "Gecmisten gunumuze aydinlatma araclarini tanir" }, { kod: "F.B.4.5.3.1", aciklama: "Ses kaydeden teknolojileri ornekler" }] }, sosyal: { konu: "6. Unite: Etkin Vatandaslik", kazanimlar: [{ kod: "SB.4.6.2", aciklama: "Vatandaslik gorevlerini ornekler" }, { kod: "SB.4.6.3", aciklama: "Toplumsal birlik ve dayanismayi aciklar" }] }, ...yanBrans(2) },
  31: { turkce: T_DOGA, matematik: { konu: "6. Unite: Veri Isleme / Cevre Olcme", kazanimlar: [{ kod: "M.4.3.1.1", aciklama: "Veri toplar ve tabloya isler" }, { kod: "M.4.2.3.1", aciklama: "Cevre uzunlugunu hesaplar" }] }, fen: { konu: "6. Unite: Insan ve Cevre", kazanimlar: [{ kod: "F.B.4.6.1.1", aciklama: "Insan ve cevre iliskisini aciklar" }] }, sosyal: { konu: "6. Unite: Etkin Vatandaslik", kazanimlar: [{ kod: "SB.4.6.2", aciklama: "Vatandaslik gorevlerini ornekler" }, { kod: "SB.4.6.3", aciklama: "Toplumsal birlik ve dayanismayi aciklar" }] }, ...yanBrans(3) },
  32: { turkce: T_DOGA, matematik: { konu: "6. Unite: Veri Isleme / Cevre Olcme", kazanimlar: [{ kod: "M.4.3.1.1", aciklama: "Veri toplar ve tabloya isler" }, { kod: "M.4.2.3.1", aciklama: "Cevre uzunlugunu hesaplar" }] }, fen: { konu: "6. Unite: Insan ve Cevre", kazanimlar: [{ kod: "F.B.4.6.1.1", aciklama: "Insan ve cevre iliskisini aciklar" }] }, sosyal: { konu: "6. Unite: Etkin Vatandaslik", kazanimlar: [{ kod: "SB.4.6.2", aciklama: "Vatandaslik gorevlerini ornekler" }, { kod: "SB.4.6.3", aciklama: "Toplumsal birlik ve dayanismayi aciklar" }] }, ...yanBrans(4) },
  33: { turkce: T_DOGA, matematik: { konu: "6. Unite: Alan Olcme / Tartma / Sivi Olcme", kazanimlar: [{ kod: "M.4.3.8.1", aciklama: "Alan olcmeyi ogrenir" }, { kod: "M.4.3.6.1", aciklama: "Tartma ve sivi olcmeyi yapar" }] }, fen: { konu: "6. Unite: Insan ve Cevre", kazanimlar: [{ kod: "F.B.4.6.1.1", aciklama: "Insan ve cevre iliskisini aciklar" }] }, sosyal: { konu: "7. Unite: Kuresel Baglantilar", kazanimlar: [{ kod: "SB.4.7.2", aciklama: "Diger ulkelerle iliskilerimizi ornekler" }] }, ...yanBrans(1) },
  34: { turkce: T_DOGA, matematik: { konu: "6. Unite: Alan Olcme / Tartma / Sivi Olcme", kazanimlar: [{ kod: "M.4.3.8.1", aciklama: "Alan olcmeyi ogrenir" }, { kod: "M.4.3.6.1", aciklama: "Tartma ve sivi olcmeyi yapar" }] }, fen: { konu: "7. Unite: Basit Elektrik Devreleri", kazanimlar: [{ kod: "F.B.4.7.1.1", aciklama: "Basit bir elektrik devresi kurar" }] }, sosyal: { konu: "7. Unite: Kuresel Baglantilar", kazanimlar: [{ kod: "SB.4.7.2", aciklama: "Diger ulkelerle iliskilerimizi ornekler" }] }, ...yanBrans(2) },
  35: { turkce: T_DOGA, matematik: { konu: "6. Unite: Alan Olcme / Tartma / Sivi Olcme", kazanimlar: [{ kod: "M.4.3.8.1", aciklama: "Alan olcmeyi ogrenir" }, { kod: "M.4.3.6.1", aciklama: "Tartma ve sivi olcmeyi yapar" }] }, fen: { konu: "7. Unite: Basit Elektrik Devreleri", kazanimlar: [{ kod: "F.B.4.7.1.1", aciklama: "Basit bir elektrik devresi kurar" }] }, sosyal: { konu: "7. Unite: Kuresel Baglantilar", kazanimlar: [{ kod: "SB.4.7.2", aciklama: "Diger ulkelerle iliskilerimizi ornekler" }] }, ...yanBrans(3) },
  36: { turkce: T_DOGA, matematik: { konu: "6. Unite: Alan Olcme / Tartma / Sivi Olcme", kazanimlar: [{ kod: "M.4.3.8.1", aciklama: "Alan olcmeyi ogrenir" }, { kod: "M.4.3.6.1", aciklama: "Tartma ve sivi olcmeyi yapar" }] }, fen: { konu: "7. Unite: Basit Elektrik Devreleri", kazanimlar: [{ kod: "F.B.4.7.1.1", aciklama: "Basit bir elektrik devresi kurar" }] }, sosyal: { konu: "7. Unite: Kuresel Baglantilar", kazanimlar: [{ kod: "SB.4.7.2", aciklama: "Diger ulkelerle iliskilerimizi ornekler" }] }, ...yanBrans(4) },
  37: { turkce: { konu: "Yil Sonu: Okuma Senligi", kazanimlar: [{ kod: "ETK", aciklama: "Kitap okuma ve paylasma etkinligi" }] }, matematik: { konu: "Yil Sonu: Matematik Oyunlari", kazanimlar: [{ kod: "ETK", aciklama: "Zeka ve matematik oyunlari etkinligi" }] }, fen: { konu: "Yil Sonu: Bilimsel Etkinlik", kazanimlar: [{ kod: "ETK", aciklama: "Fen ve teknoloji deney/gozlem etkinligi" }] }, sosyal: { konu: "Yil Sonu: Degerlendirme", kazanimlar: [{ kod: "ETK", aciklama: "Yil boyu ogrenilenleri degerlendirme" }] }, ingilizce: { konu: "Yil Sonu: Sarki ve Oyun", kazanimlar: [{ kod: "ETK", aciklama: "Ingilizce sarki ve kelime oyunlari" }] }, dkab: { konu: "Yil Sonu: Degerler Etkinligi", kazanimlar: [{ kod: "ETK", aciklama: "Degerler ve paylasma etkinligi" }] }, insanhak: { konu: "Yil Sonu: Degerlendirme", kazanimlar: [{ kod: "ETK", aciklama: "Haklar ve sorumluluklar degerlendirmesi" }] }, trafik: { konu: "Yil Sonu: Trafik Oyunu", kazanimlar: [{ kod: "ETK", aciklama: "Trafik kurallari oyun ve etkinligi" }] }, gorsel: { konu: "Yil Sonu: Resim Sergisi", kazanimlar: [{ kod: "ETK", aciklama: "Yil sonu resim sergisi hazirlama" }] }, muzik: { konu: "Yil Sonu: Muzik Dinletisi", kazanimlar: [{ kod: "ETK", aciklama: "Yil sonu sarki ve muzik dinletisi" }] }, beden: { konu: "Yil Sonu: Sportif Faaliyetler", kazanimlar: [{ kod: "ETK", aciklama: "Sportif oyunlar ve yarismalar" }] } },
  38: { turkce: { konu: "Yil Sonu: Karne ve Veda", kazanimlar: [{ kod: "ETK", aciklama: "Yil sonu degerlendirme ve veda etkinligi" }] }, matematik: { konu: "Yil Sonu: Genel Tekrar", kazanimlar: [{ kod: "ETK", aciklama: "Eglenceli genel tekrar oyunlari" }] }, fen: { konu: "Yil Sonu: Bilim Senligi", kazanimlar: [{ kod: "ETK", aciklama: "Bilim senligi ve proje sunumu" }] }, sosyal: { konu: "Yil Sonu: Gezi/Etkinlik", kazanimlar: [{ kod: "ETK", aciklama: "Cevre gezisi ve sosyal etkinlik" }] }, ingilizce: { konu: "Yil Sonu: Eglence", kazanimlar: [{ kod: "ETK", aciklama: "Ingilizce eglence etkinligi" }] }, dkab: { konu: "Yil Sonu: Paylasma", kazanimlar: [{ kod: "ETK", aciklama: "Paylasma ve yardimlasma etkinligi" }] }, insanhak: { konu: "Yil Sonu: Etkinlik", kazanimlar: [{ kod: "ETK", aciklama: "Degerler ve haklar etkinligi" }] }, trafik: { konu: "Yil Sonu: Degerlendirme", kazanimlar: [{ kod: "ETK", aciklama: "Trafik bilgisi degerlendirme" }] }, gorsel: { konu: "Yil Sonu: Sergi", kazanimlar: [{ kod: "ETK", aciklama: "Yil sonu sanat sergisi" }] }, muzik: { konu: "Yil Sonu: Sarki", kazanimlar: [{ kod: "ETK", aciklama: "Yil sonu muzik etkinligi" }] }, beden: { konu: "Yil Sonu: Spor Senligi", kazanimlar: [{ kod: "ETK", aciklama: "Spor senligi ve oyunlar" }] } }
};